### ISSUE TITLE
ImportError: cannot import name downsample

### ISSUE THREAD

**Issue by SeekPoint** [kimiyoung/planetoid#1]
rzai@rzai00:~/prj/planetoid$ python test_trans.py
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled, cuDNN 5005)
Traceback (most recent call last):
  File "test_trans.py", line 3, in <module>
    from trans_model import trans_model as model
  File "/home/rzai/prj/planetoid/trans_model.py", line 2, in <module>
    import lasagne
  File "/usr/local/lib/python2.7/dist-packages/lasagne/__init__.py", line 19, in <module>
    from . import layers
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/__init__.py", line 7, in <module>
    from .pool import *
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/pool.py", line 6, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name downsample
rzai@rzai00:~/prj/planetoid$

**Comment by kimiyoung** [comment]
I think you can re-install lasagne, http://lasagne.readthedocs.io/en/latest/user/installation.html

**Comment by SeekPoint** [comment]
it works!

**Comment by HelloGeorge** [comment]
可以说一下你是怎么解决的吗，我也遇到了这个问题

**Comment by kimiyoung** [comment]
Try reintsalling or upgrading lasagne.

**Comment by HelloGeorge** [comment]
It works,thank you!

**Comment by slychief** [comment]
In Theano 9 the downsample module has been moved or renamed. 

`from theano.tensor.signal import pool`

This issue was also raised in another project:
https://github.com/sklearn-theano/sklearn-theano/issues/97

This is a rather severe issue, because keras already uses the `pool` reference. Thus, one has to decide between using Lasagne (Theano 0.8) or keras (Theano 0.9).

**Comment by hangingter** [comment]
Commented out :
“from theano.tensor.signal.pool import downsample”
and change this:
"from theano.tensor.signal.pool import pool_2d"
