### ISSUE TITLE
about citeseer

### ISSUE THREAD

**Issue by FOURIERWANG** [kimiyoung/planetoid#10]
When I use citeseer data, it will report error that index 3312 is out of bounds for dim with size 3312. Or expected dim 0 size 3327,got 3312. I don't know whether citeseer has 3312 or 3327 nodes. Please help me to solve the question.Thanks

**Comment by FOURIERWANG** [comment]
Maybe I find the way to solve it.

**Comment by FOURIERWANG** [comment]
Maybe I find the way to solve it.

**Comment by FOURIERWANG** [comment]
Maybe I find the way to solve it.

**Comment by FOURIERWANG** [comment]
Maybe I find the way to solve it.

**Comment by FOURIERWANG** [comment]
Maybe I find the way to solve it.

**Comment by FOURIERWANG** [comment]
Maybe I find the way to solve it.

**Comment by FOURIERWANG** [comment]
Maybe I find the way to solve it.

**Comment by ShengdingHu** [comment]
The number of labeled nodes are 3312， and  the number of total nodes are 3327, some codebase use the one hot encoding [0,...,1,...,0] and crossentropy so the missing label nodes's label are all zero in this way. Other codebase use the integer label, they may remove the unlabeled ones to avoid error.
